<a href="https://colab.research.google.com/github/xiomiliseth02-beep/Estad-stica-I/blob/main/bono_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MONEJO DE MODULOS INTEGRADOS

#Numpy: se usa principalmente para trabajar con datos numéricos de forma rápida, eficiente y estructurada. un objeto tipo numpy es un arreglo base para hacer matemáticas y manipular datos de Python.

#Pandas: se usa para trabajar con datos estructurados (como tablas de excel o bases de datos.). Un objeto tipo pandas permite cargar, limpiar, transformar y analizar datos. la usamos para bases de datos relacionales.

In [ ]:
import numpy as np

In [ ]:
resistencia_concreto = np.array([25.4, 28.1, 24.8, 27.5, 29.2, 26.0, 27.1, 29.8])
resistencia_materiales = np.array([[25.4, 28.1],  [24.8, 27.5],  [29.2, 26.0],  ])

print("Resistencia en Mpa (Megapascales):", resistencia_concreto)
print("Resistencia en Mpa (megapascales)", resistencia_materiales)

Resistencia en Mpa (Megapascales): [25.4 28.1 24.8 27.5 29.2 26.  27.1 29.8]
Resistencia en Mpa (megapascales) [[25.4 28.1]
 [24.8 27.5]
 [29.2 26. ]]


In [ ]:
Lista_resistencia = [25.4, 28.1, 24.8, 27.5, 29.2, 26.0, 27.1]

In [ ]:
resistencia_concreto*2 #multiplica el array por dos

array([50.8, 56.2, 49.6, 55. , 58.4, 52. , 54.2, 59.6])

In [ ]:
Lista_resistencia*2 #lista concatenada

[25.4,
 28.1,
 24.8,
 27.5,
 29.2,
 26.0,
 27.1,
 25.4,
 28.1,
 24.8,
 27.5,
 29.2,
 26.0,
 27.1]

In [ ]:
resistencia_concreto.shape #dimension de mi arreglo

(8,)

In [ ]:
resistencia_materiales.shape #arreglo de de tres componentes cada una con dos elementos

(3, 2)

In [ ]:
resistencia_concreto.ndim #numero de dimensiones

1

In [ ]:
resistencia_materiales.ndim #numero de elementos por cada componente

2

In [ ]:
resistencia_materiales.dtype #objeto tipo float

dtype('float64')

In [ ]:
resistencia_materiales.size #cantidad de elementos de todas las componentes

6

In [ ]:
np.zeros((3,5)) #aproximacion de resistencia de materiales

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
resistencia_concreto[-1]

np.float64(29.8)

In [ ]:
resistencia_concreto[0:2]

array([25.4, 28.1])

In [ ]:
resistencia_concreto.reshape(2,4)

array([[25.4, 28.1, 24.8, 27.5],
       [29.2, 26. , 27.1, 29.8]])

In [ ]:
np.concatenate([resistencia_concreto, resistencia_concreto])

array([25.4, 28.1, 24.8, 27.5, 29.2, 26. , 27.1, 29.8, 25.4, 28.1, 24.8,
       27.5, 29.2, 26. , 27.1, 29.8])

In [ ]:
np.concatenate(resistencia_concreto.reshape(2,4))

array([25.4, 28.1, 24.8, 27.5, 29.2, 26. , 27.1, 29.8])

In [ ]:
resistencia_materiales[0,1]

np.float64(28.1)

In [ ]:
resistencia_materiales[:,0]

array([25.4, 24.8, 29.2])

In [ ]:
a = np.array([24.8, 27.5])
b = np.array([25.4, 28.1])
a + b

array([50.2, 55.6])

In [ ]:
a*b

array([629.92, 772.75])

In [ ]:
resistencia_materiales*a

array([[629.92, 772.75],
       [615.04, 756.25],
       [724.16, 715.  ]])

In [ ]:
[x*2 for x in Lista_resistencia]

[50.8, 56.2, 49.6, 55.0, 58.4, 52.0, 54.2]

In [ ]:
print(np.mean(resistencia_concreto), np.median(resistencia_concreto), np.std(resistencia_concreto), np.sum(resistencia_concreto), np.min(resistencia_concreto), np.max(resistencia_concreto), np.max(resistencia_concreto))

27.2375 27.3 1.662030008754355 217.9 24.8 29.8 29.8


In [ ]:
resistencia_materiales.flatten()

array([25.4, 28.1, 24.8, 27.5, 29.2, 26. ])

In [ ]:
np.dot(a, b)

np.float64(1402.67)

In [ ]:
c = np.array([[24.8, 27.5], [25.4, 28.1]])
np.linalg.inv(c)


array([[-17.34567901,  16.97530864],
       [ 15.67901235, -15.30864198]])

In [ ]:
np.linalg.matrix_transpose(c)

array([[24.8, 25.4],
       [27.5, 28.1]])

In [ ]:
np.random.randint(0,5)

0

In [ ]:
np.random.rand(5)

array([0.66994157, 0.72222711, 0.20499005, 0.12724763, 0.63447066])

In [ ]:
np.random.randn(5)

array([ 0.1198767 ,  0.74957319, -1.41629605,  0.29674417, -0.89180626])

In [ ]:
resistencia_concreto[resistencia_concreto > 26]


array([28.1, 27.5, 29.2, 27.1, 29.8])

In [ ]:
resistencia_concreto[(resistencia_concreto > 26) & (resistencia_concreto < 28)]

array([27.5, 27.1])

In [ ]:
np.where(resistencia_concreto > 26, 1, 0)

array([0, 1, 0, 1, 1, 0, 1, 1])

In [ ]:
np.where(resistencia_concreto > 26, resistencia_concreto, 0)

array([ 0. , 28.1,  0. , 27.5, 29.2,  0. , 27.1, 29.8])

In [ ]:
import pandas as pd

In [ ]:
dm = pd.DataFrame({
    'Modelo': ['Renault 4', 'Kia', 'Renault 4', 'Kia', 'Renault 4', 'Kia'],
    'Combustible': ['Gasolina', 'Diesel', 'Gasolina', 'Diesel', 'Gasolina', 'Diesel'],
    'RPM Prueba': [2500, 3000, 2800, 3200, 2600, 3100],
    'Temperatura C': [85, 92, 88, 95, 86, 94],
    'Inspeccion Aprobada': [True, True, False, True, True, False]
})
dm

,Modelo,Combustible,RPM Prueba,Temperatura C,Inspeccion Aprobada
0,Renault 4,Gasolina,2500,85,True
1,Kia,Diesel,3000,92,True
2,Renault 4,Gasolina,2800,88,False
3,Kia,Diesel,3200,95,True
4,Renault 4,Gasolina,2600,86,True
5,Kia,Diesel,3100,94,False


In [ ]:
dm.head(3)

,Modelo,Combustible,RPM Prueba,Temperatura C,Inspeccion Aprobada
0,Renault 4,Gasolina,2500,85,True
1,Kia,Diesel,3000,92,True
2,Renault 4,Gasolina,2800,88,False


In [ ]:
dm.tail(2)

,Modelo,Combustible,RPM Prueba,Temperatura C,Inspeccion Aprobada
4,Renault 4,Gasolina,2600,86,True
5,Kia,Diesel,3100,94,False


In [ ]:
dm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Modelo               6 non-null      object
 1   Combustible          6 non-null      object
 2   RPM Prueba           6 non-null      int64 
 3   Temperatura C        6 non-null      int64 
 4   Inspeccion Aprobada  6 non-null      bool  
dtypes: bool(1), int64(2), object(2)
memory usage: 330.0+ bytes


In [ ]:
dm.describe()

,RPM Prueba,Temperatura C
count,6.000000,6.000000
mean,2866.666667,90.000000
std,280.475786,4.242641
min,2500.000000,85.000000
25%,2650.000000,86.500000
50%,2900.000000,90.000000
75%,3075.000000,93.500000
max,3200.000000,95.000000


In [ ]:
dm.shape

(6, 5)

In [ ]:
dm['Combustible']

,Combustible
0,Gasolina
1,Diesel
2,Gasolina
3,Diesel
4,Gasolina
5,Diesel


In [ ]:
dm[['Combustible', 'Inspeccion Aprobada']]

,Combustible,Inspeccion Aprobada
0,Gasolina,True
1,Diesel,True
2,Gasolina,False
3,Diesel,True
4,Gasolina,True
5,Diesel,False


In [ ]:
dm[dm['RPM Prueba'] > 3000]

,Modelo,Combustible,RPM Prueba,Temperatura C,Inspeccion Aprobada
3,Kia,Diesel,3200,95,True
5,Kia,Diesel,3100,94,False


In [ ]:
dm[(dm['RPM Prueba'] > 2800) & (dm['RPM Prueba'] < 3500)]

,Modelo,Combustible,RPM Prueba,Temperatura C,Inspeccion Aprobada
1,Kia,Diesel,3000,92,True
3,Kia,Diesel,3200,95,True
5,Kia,Diesel,3100,94,False


In [ ]:
dm1 = pd.DataFrame({
    'Modelo': ['Renault 4', 'Kia', 'Renault 4', 'Kia', 'Renault 4', 'Kia'],
    'Combustible': ['Gasolina', None , 'Gasolina', 'Diesel', 'Gasolina', 'Diesel'],
    'RPM_Prueba': [np.nan , 3000, 2800, 3200, np.nan, 3100],
    'Temperatura_C': [85, 92, None, 95, 86, 94],
    'Inspeccion_Aprobada': [True, True, False, True, True, False]
})
dm1

,Modelo,Combustible,RPM_Prueba,Temperatura_C,Inspeccion_Aprobada
0,Renault 4,Gasolina,NaN,85.0,True
1,Kia,None,3000.0,92.0,True
2,Renault 4,Gasolina,2800.0,NaN,False
3,Kia,Diesel,3200.0,95.0,True
4,Renault 4,Gasolina,NaN,86.0,True
5,Kia,Diesel,3100.0,94.0,False


In [ ]:
dm1.isnull()

,Modelo,Combustible,RPM_Prueba,Temperatura_C,Inspeccion_Aprobada
0,False,False,True,False,False
1,False,True,False,False,False
2,False,False,False,True,False
3,False,False,False,False,False
4,False,False,True,False,False
5,False,False,False,False,False


In [ ]:
dm1.isnull().sum()

,0
Modelo,0
Combustible,1
RPM_Prueba,2
Temperatura_C,1
Inspeccion_Aprobada,0


In [ ]:
dm2 = dm1.dropna()
dm2

,Modelo,Combustible,RPM_Prueba,Temperatura_C,Inspeccion_Aprobada
3,Kia,Diesel,3200.0,95.0,True
5,Kia,Diesel,3100.0,94.0,False


In [ ]:
dm1.dropna(subset=['RPM_Prueba'])

,Modelo,Combustible,RPM_Prueba,Temperatura_C,Inspeccion_Aprobada
1,Kia,None,3000.0,92.0,True
2,Renault 4,Gasolina,2800.0,NaN,False
3,Kia,Diesel,3200.0,95.0,True
5,Kia,Diesel,3100.0,94.0,False


In [ ]:
dm1['RPM_Prueba'] = dm1['RPM_Prueba'].fillna(dm1['RPM_Prueba'].mean())
dm1['Combustible'] = dm1['Combustible'].fillna('desconocido')
dm1

,Modelo,Combustible,RPM_Prueba,Temperatura_C,Inspeccion_Aprobada
0,Renault 4,Gasolina,3025.0,85.0,True
1,Kia,desconocido,3000.0,92.0,True
2,Renault 4,Gasolina,2800.0,NaN,False
3,Kia,Diesel,3200.0,95.0,True
4,Renault 4,Gasolina,3025.0,86.0,True
5,Kia,Diesel,3100.0,94.0,False


In [ ]:
dm2 = dm1['Combustible'].drop_duplicates()
dm2

,Combustible
0,Gasolina
1,desconocido
3,Diesel


#Uso en Ciencia de Datos: Ventajas y Desventajas de NumPy y Pandas
Tanto NumPy como Pandas constituyen la columna vertebral del ecosistema de la Ciencia de Datos y el Machine Learning en Python. Sin estas librerías, la implementación de algoritmos de optimización, predicción y análisis estadístico sería inviable debido a las limitaciones de rendimiento y memoria de las estructuras nativas de Python (como las listas).

NumPy (Numerical Python)
Uso en Ciencia de Datos:
Es la librería fundamental para el cómputo científico y el álgebra lineal. En la Ciencia de Datos, casi cualquier algoritmo (desde una regresión lineal hasta una red neuronal profunda) traduce los datos de entrada a arreglos multidimensionales (matrices o tensores). NumPy proporciona la estructura y las funciones matemáticas necesarias para realizar operaciones masivas sobre estos tensores (como el producto punto, inversiones de matrices y cálculo de gradientes) a velocidades extremadamente altas.

implementación de algoritmos:

Ventajas

Velocidad y Rendimiento (C-Engine): Sus bloques internos están escritos en C. Las operaciones se ejecutan a nivel de código compilado, evitando la lentitud del tipado dinámico de Python.

Vectorización: Permite aplicar operaciones matemáticas a todo un bloque de datos simultáneamente sin necesidad de usar bucles for. Esto optimiza drásticamente el tiempo de ejecución del algoritmo.

Eficiencia en Memoria: Almacena los datos en ubicaciones contiguas de la memoria física y exige un tipo de dato fijo, reduciendo drásticamente el consumo de recursos de cómputo.

Desventajas:

Homogeneidad estricta: Un arreglo de NumPy solo puede contener un único tipo de dato (por ejemplo, exclusivamente float64). No permite mezclar de forma eficiente texto con variables numéricas.

Ausencia de etiquetas: Los datos se indexan únicamente por su posición numérica. No cuenta con nombres de columnas ni de filas, lo que dificulta el manejo y la comprensión de bases de datos tabulares complejas.

Pandas (Panel Data)
Uso en Ciencia de Datos:
Se especializa en la manipulación, estructuración y Análisis Exploratorio de Datos (EDA). Es la herramienta clave en la fase de preprocesamiento de un proyecto de Ciencia de Datos. Antes de entrenar un algoritmo, los datos crudos suelen venir con ruidos o imperfecciones; Pandas permite cargar bases de datos relacionales, limpiar registros, filtrar filas bajo condiciones lógicas, agrupar variables y solucionar el problema de los datos faltantes (NaN).

implementación de algoritmos:

Ventajas  

Flexibilidad (Heterogeneidad): Un DataFrame permite alinear en una sola estructura tabular columnas de texto, números enteros, decimales y booleanos, simulando el comportamiento de una base de datos SQL o una hoja de cálculo.

Etiquetado intuitivo: Facilita el acceso, la manipulación y el filtrado de la información mediante nombres explícitos de variables (columnas) e índices, haciendo el código más legible y menos propenso a errores humanos.

Herramientas avanzadas de alineación y limpieza: Cuenta con funciones nativas sumamente potentes para fusionar tablas (merge), agrupar categorías (groupby) y tratar series temporales o datos nulos de manera inmediata.

Desventajas:

Alto consumo de memoria: Pandas genera copias en memoria para muchas de sus transformaciones y arrastra demasiados metadatos (índices, nombres). No está diseñado para trabajar con Big Data (volúmenes de datos que superen la memoria RAM del equipo).

Menor velocidad en cálculo puro: Para evaluar ecuaciones matemáticas complejas o iteraciones algorítmicas, Pandas es notablemente más lento que NumPy debido a su sobrecarga estructural. Por ello, la regla general en Ciencia de Datos es usar Pandas para limpiar el dataset y, justo antes de ingresar el algoritmo, convertirlo a un arreglo numérico puro usando .to_numpy().